title:   Mike Baran
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  Sata analyst / business intelligence analyst ready and able to deliver innovative technical solutions that enhance the experience of both customers and analytic professionals. Proficient in SQL, Python, and Power BI, with a validated competence to automate dashboards, streamline processes, and provide tactical direction to stakeholders using easy-to-understand language. Skilled in analyzing behavioral data, identifying business gaps, and developing solutions that meet the needs of both internal and external stakeholders.
  <br><br><br>
  <a href="www.linkedin.com/in/mike-baran-b6136a278">View My LinkedIn Profile</a>
  <br><br><br>
  <a href="https://public.tableau.com/app/profile/mike.baran7793/vizzes">View My Tableau Work Samples</a>
  <br><br><br>
  <a href="https://www.notion.so/mikebaran/Portfolio-3a7abd87f01e463a993a41833cd0e1b6">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
